### ISSUE TITLE
Seems its not working in a nextjs project

### ISSUE THREAD

**Issue by pitops** [GavinJoyce/tailwindcss-question-mark#2]
Hi, I followed the instruction, added it to the plugin list but it's not showing anything. Is there anything special to do in react/next projects?

**Comment by GavinJoyce** [comment]
@pitops did you manage to get it working?

**Comment by pitops** [comment]
Yeah so i use an `nx monorepo` with `NextJS` and i need to add this into `postcss.config.js`

```
module.exports = {
  plugins: {
    tailwindcss: { config: './apps/eshop/tailwind.config.js' },
    autoprefixer: {},
  },
};

```

> Basically the path in NX is from the root of the project and it was not being picked up automatically.
