### ISSUE TITLE
Demo is failing.

### ISSUE THREAD

**Issue by chan18** [GavinJoyce/tailwindcss-question-mark#6]
![image](https://user-images.githubusercontent.com/13510817/128593688-454c8f6c-c88e-487d-8301-14f7b168ee18.png)

demo link:- https://play.tailwindcss.com/5a9dYkfqd4

**Comment by GavinJoyce** [comment]
Fixed: https://play.tailwindcss.com/fXhD65EpG4?layout=horizontal
